import { SlashCommandBuilder, ChatInputCommandInteraction, EmbedBuilder, AutocompleteInteraction } from 'discord.js';
import { Command, DisasterSeverity, USRegion } from '../../types';
import { DatabaseManager } from '../../database/DatabaseManager';
import { Logger } from '../../utils/Logger';
import { DisasterGenerator } from '../../utils/DisasterGenerator';

export class AdminDisasterCommand implements Command {
  public data = new SlashCommandBuilder()
    .setName('admin-disaster')
    .setDescription('Generate a disaster event (Admin only)')
    .addStringOption(option =>
      option.setName('severity')
        .setDescription('Disaster severity level')
        .setRequired(false)
        .addChoices(
          { name: 'Random', value: 'random' },
          { name: 'Very Small', value: 'very_small' },
          { name: 'Small', value: 'small' },
          { name: 'Medium', value: 'medium' },
          { name: 'Large', value: 'large' },
          { name: 'Major', value: 'major' },
          { name: 'Catastrophic', value: 'catastrophic' }
        )
    )
    .addStringOption(option =>
      option.setName('region')
        .setDescription('Affected region')
        .setRequired(false)
        .addChoices(
          { name: 'Random', value: 'random' },
          { name: 'New York', value: 'new_york' },
          { name: 'Texas', value: 'texas' },
          { name: 'Southern California', value: 'southern_california' },
          { name: 'Northern California', value: 'northern_california' },
          { name: 'Florida', value: 'florida' },
          { name: 'New England', value: 'new_england' },
          { name: 'Cascadia', value: 'cascadia' },
          { name: 'Carolina', value: 'carolina' },
          { name: 'Illinois', value: 'illinois' },
          { name: 'Pennsylvania', value: 'pennsylvania' },
          { name: 'Dixieland', value: 'dixieland' },
          { name: 'Ohio', value: 'ohio' },
          { name: 'Georgia', value: 'georgia' },
          { name: 'Virginia', value: 'virginia' },
          { name: 'New Jersey', value: 'new_jersey' },
          { name: 'Maryland', value: 'maryland' },
          { name: 'Oklahoma', value: 'oklahoma' },
          { name: 'Michigan', value: 'michigan' },
          { name: 'Dakota', value: 'dakota' },
          { name: 'Nuevo Arizona', value: 'nuevo_arizona' },
          { name: 'Tennessee', value: 'tennessee' },
          { name: 'Colorado', value: 'colorado' },
          { name: 'Indiana', value: 'indiana' },
          { name: 'Wisconsin', value: 'wisconsin' }
        )
    );

  public async execute(
    interaction: ChatInputCommandInteraction,
    dbManager: DatabaseManager,
    logger: Logger
  ): Promise<void> {
    let severity = interaction.options.getString('severity') as DisasterSeverity | 'random' | null;
    const region = interaction.options.getString('region') as USRegion | null;

    try {
      const disasterGenerator = new DisasterGenerator(logger);

      // Handle random severity
      if (!severity || severity === 'random') {
        severity = disasterGenerator.selectDisasterSeverity();
      }

      const disaster = disasterGenerator.generateDisaster(severity as DisasterSeverity, region || 'random');

      dbManager.logAdminAction(
        interaction.user.id,
        'GENERATE_DISASTER',
        `Generated ${severity} disaster in ${region || 'random region'}: ${disaster.title}`
      );

      const embed = new EmbedBuilder()
        .setColor(0xff4500)
        .setTitle(`🌪️ ${disaster.title}`)
        .setDescription(disaster.description)
        .addFields(
          { name: '📊 Severity', value: disaster.type.replace('_', ' ').toUpperCase(), inline: true },
          { name: '🏷️ Category', value: disaster.category.toUpperCase(), inline: true },
          { name: '⏱️ Timeline', value: disaster.timeline, inline: true },
          { name: '💀 Est. Casualties', value: disaster.estimatedCasualties.toLocaleString(), inline: true },
          { name: '💰 Economic Cost', value: `$${disaster.economicCost.toFixed(1)}B`, inline: true },
          { name: '🗺️ Affected Regions', value: disaster.affectedRegions.join(', '), inline: false }
        )
        .setFooter({ text: `Generated by ${interaction.user.tag}` })
        .setTimestamp();

      await interaction.reply({ embeds: [embed] });

      logger.info(`Admin ${interaction.user.tag} generated disaster: ${disaster.title}`);

    } catch (error) {
      logger.error('Error generating disaster:', { error: error as Error });
      
      // More detailed error logging
      if (error instanceof Error) {
        logger.error('Error message:', { metadata: { message: error.message } });
        logger.error('Error stack:', { metadata: { stack: error.stack } });
      }

      const embed = new EmbedBuilder()
        .setColor(0xff0000)
        .setTitle('❌ Error Generating Disaster')
        .setDescription('An error occurred while generating the disaster. Please try again.')
        .setTimestamp();

      if (interaction.replied || interaction.deferred) {
        await interaction.followUp({ embeds: [embed] });
      } else {
        await interaction.reply({ embeds: [embed] });
      }
    }
  }

  public async autocomplete(
    interaction: AutocompleteInteraction,
    dbManager: DatabaseManager,
    logger: Logger
  ): Promise<void> {
    await interaction.respond([]);
  }
}